CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    default_uses INTEGER NOT NULL,
    bang_uses INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS bangs (
    id INTEGER PRIMARY KEY,
    owner INTEGER REFERENCES users (id) ON DELETE CASCADE,
    bang VARCHAR NOT NULL,
    value VARCHAR NOT NULL,
    uses INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS quick_links (
    id INTEGER PRIMARY KEY,
    owner INTEGER REFERENCES users (id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    url VARCHAR NOT NULL
);
